#!/bin/sh


. /afs/slackers.net/projects/infrastructure/etc/functions
getToken webmaster webmaster 36h

#klist
#tokens

exec /afs/slackers.net/projects/clubcar/release/current/script/process/spawner \
  mongrel \
  --environment=production \
  --instances=1 \
  --address=127.0.0.1 \
  --port=3000

